version: '3.8'

services:
  web:
    build: ./services/web
    command: python manage.py run -h 0.0.0.0:7070
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 7070:7070
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=arima
      - POSTGRES_PASSWORD=arima
      - POSTGRES_DB=movies
  pgadmin:
    image: dpage/pgadmin4:4.30
    container_name: pgadmin_flask
    restart: always
    environment:
        PGADMIN_DEFAULT_EMAIL: "arima@email"
        PGADMIN_DEFAULT_PASSWORD: "arima-password"
        PGADMIN_LISTEN_PORT: 80
    ports:
        - 8080:80
    volumes:
        - pgadmin-flask-data:/var/lib/pgadmin
    links:
        - db:pgsql-server

volumes:
  postgres_data:
  pgadmin-flask-data:
